spring:
  datasource:
      url: jdbc:sqlserver://11.11.7.142:1433;databaseName=student-management-tri
      username: tm_app
      password: Sql#1234
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
jooq:
  sql:
    dialect: SQLSERVER
logging:
  file:
    path: com/galaxy/studentmanagement
    name: applicationn.log
  level:
    root: INFO
    com.galaxy.studentmanagement: INFO
    org:
      jooq:
        tools:
          LoggerListener: OFF
